vagrant/item_catalog/webapp/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextAreaField, PasswordField, BooleanField, Field
from wtforms.widgets import TextInput
from wtforms.validators import DataRequired, Length, EqualTo, URL

from .models import User

class TagListField(Field):
    'Creates a field to handle tags in forms'
    widget = TextInput()

    def _value(self):
        if self.data:
            return u', '.join(self.data)
        else:
            return u''

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = [x.strip() for x in valuelist[0].split(',')]
        else:
            self.data = []

class OpenIDForm(FlaskForm):
    'Form for OpenID users'
    openid = StringField('OpenID Url', [DataRequired(), URL()])

class LoginForm(FlaskForm):
    'Form to login to the site'
    username = StringField('Username', [
        DataRequired(), Length(max=255)
    ])
    password = PasswordField('Password', [DataRequired()])
    remember = BooleanField("Remember Me")

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # if user doesn't exist
        user = User.query.filter_by(
            username=self.username.data
        ).first()
        if not user:
            self.username.errors.append(
                'Invalid username or password'
            )
            return False

        # Do passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append(
                'Invalid username or password'
            )
            return False

        return True

class RegisterForm(FlaskForm):
    'Form to add users to the site'
    username = StringField( 'username', [
        DataRequired(),
        Length(max=255)
    ])
    password = PasswordField('password', [
        DataRequired(),
        Length(min=8)
    ])
    confirm = PasswordField('Confirm Password', [
        DataRequired(),
        EqualTo('password')
    ])
    recaptcha = RecaptchaField()

    def validate(self):
        check_validate = super(RegisterForm, self).validate()

        #if validation fails
        if not check_validate:
            return False

        user = User.query.filter_by(
            username=self.username.data
        ).first()

        # Is the username already in use?
        if user:
            self.username.errors.append(
                "User with that username already exists"
            )
            return False

        return True

class ItemForm(FlaskForm):
    'Form to create or edit items'
    title = StringField('Name', [
        DataRequired(),
        Length(max=255)
    ])
    description = StringField('Description', [Length(max=255)])
    tags = TagListField('Tags')
    price = StringField('Price', [DataRequired()])

    def validate(self):
        check_validate = super(ItemForm, self).validate()

        if not check_validate:
            return False

        return True

vagrant/item_catalog/webapp/__init__.py
from config import DevConfig
from flask import Flask
from flask_login import current_user
from flask_principal import identity_loaded, UserNeed, RoleNeed

from models import db
from controllers.catalog import catalog_blueprint
from controllers.main import main_blueprint
from .extensions import bcrypt, oid,login_manager, principals, rest_api
from .controllers.rest.auth import AuthApi
from .controllers.rest.item import ItemApi
def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(DevConfig)

    #initialize db and extensions
    db.init_app(app)
    bcrypt.init_app(app)
    oid.init_app(app)
    login_manager.init_app(app)
    principals.init_app(app)
    rest_api.add_resource(
    	ItemApi, 
    	'/api/post',
    	'/api/post/<int:item_id>',
    	endpoint='api'
    )
    rest_api.add_resource(
    	AuthApi, 
    	'/api/auth'
    )
    rest_api.init_app(app)

    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        # Set the identity user object
        identity.user = current_user

        # Add the UserNeed to the identity
        if hasattr(current_user, 'id'):
            identity.provides.add(UserNeed(current_user.id))

        # Add each role to the identity
        if hasattr(current_user, 'roles'):
            for role in current_user.roles:
                identity.provides.add(RoleNeed(role.name))

    #initialize app controllers
    app.register_blueprint(main_blueprint)
    app.register_blueprint(catalog_blueprint)
    
    return app

vagrant/item_catalog/webapp/controllers/catalog.py
import datetime
from os import path
from flask import Blueprint, redirect, render_template, url_for, session, flash
from flask_login import login_required, current_user
from flask_principal import Permission, UserNeed
from sqlalchemy import func

from webapp.extensions import poster_permission, admin_permission
from webapp.models import db, Item, Tag, User, tags
from webapp.forms import ItemForm

catalog_blueprint = Blueprint(
    'catalog',
    __name__,
    template_folder='../templates/catalog',
    url_prefix="/catalog"
)

def sidebar_data():
    'Gets recent created items and most used tags'
    recent = Item.query.order_by(
        Item.added_date.desc()
    ).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.item_id).label('total')
    ).join(
        tags
    ).group_by(Tag).order_by('total DESC').limit(5).all()

    return recent, top_tags

@catalog_blueprint.route('/')
@catalog_blueprint.route('/<int:page>')
def home(page=1):
    'Renders homepage of site'
    items = Item.query.order_by(
        Item.added_date.desc()
    ).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return render_template(
        'home.html',
        items=items,
        recent=recent,
        top_tags=top_tags
    )

@catalog_blueprint.route('/item/<int:item_id>', methods=['GET'])
def item(item_id):
    'Renders item page by id given'
    item = Item.query.get_or_404(item_id)
    tags = item.tags
    user = User.query.filter_by(id = item.user_id).first_or_404()
    recent, top_tags = sidebar_data()

    return render_template(
        'item.html',
        item=item,
        tags=tags,
        recent=recent,
        top_tags=top_tags,
        user=user
    )

@catalog_blueprint.route('/tag/<string:tag_name>')
def tag(tag_name):
    'List all items created with the supplied tag name'
    tag = Tag.query.filter_by(title = tag_name).first_or_404()
    items = tag.items.order_by(Item.added_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'tag.html',
        tag=tag,
        items=items,
        recent=recent,
        top_tags=top_tags
    )

@catalog_blueprint.route('/user/<string:username>')
def user(username):
    'Loads userpage by unique username'
    user = User.query.filter_by(username=username).first_or_404()
    items = user.items.order_by(Item.added_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'user.html',
        user=user,
        items=items,
        recent=recent,
        top_tags=top_tags
    )

@catalog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def new_item():
    'Allows logged in users to create new items'
    form = ItemForm()

    if form.validate_on_submit():
        new_item = Item(form.title.data)
        new_item.description = form.description.data
        new_item.added_date = datetime.datetime.now()
        new_item.price = form.price.data

        if form.tags.data:
            for item in form.tags.data:
                tag = Tag.query.filter_by(title=item).first()

                #Add the tag if it exists
                # If not, make a new tag
                if tag:
                    new_item.tags.append(tag)
                else:
                    new_tag = Tag(item)
                    new_item.tags.append(new_tag)

        new_item.user = User.query.filter_by(
            username=current_user.username
        ).one()

        db.session.add(new_item)
        db.session.commit()
        return redirect(url_for('.home'))

    return render_template('new.html', form=form)

@catalog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def edit_item(id):
    'Allows users to edit their own items or the items of others if they are an admin'
    item = Item.query.get_or_404(id)
    permission = Permission(UserNeed(item.user.id))

    # We want admins to be able to edit any item
    if permission.can() or admin_permission.can():
        form = ItemForm()

        if form.validate_on_submit():
            item.title = form.title.data
            item.description = form.description.data
            item.added_date = datetime.datetime.now()

            if form.tags.data:
                item.tags = []
                for tag_val in form.tags.data:
                    tag = Tag.query.filter_by(title=tag_val).first()

                    #Add the tag if it exists
                    # If not, make a new tag
                    if tag:
                        item.tags.append(tag)
                    else:
                        new_tag = Tag(tag_val)
                        item.tags.append(new_tag)
            
            db.session.add(item)
            db.session.commit()

            return redirect(url_for('.item', item_id=item.id))

        # Make sure the tag values are displayed and not the class representations
        tag_title_list = []
        for tag in item.tags:
            tag_title_list.append(str(tag.title))

        tag_title_list = ','.join(tag_title_list)
        return render_template('edit.html', form=form, item=item, tags=tag_title_list)

    abort(403) 

@catalog_blueprint.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def delete_item(id):  
    'Allows users to delete their own items or the items of others if they are an admin'
    item = Item.query.get_or_404(id)
    permission = Permission(UserNeed(item.user.id))

    # We want admins to be able to edit any item
    if permission.can() or admin_permission.can():
        db.session.delete(item)
        db.session.commit()

        flash("The item was successfully deleted", category="success")
        return redirect(url_for('.home'))

    abort(403)

vagrant/item_catalog/webapp/controllers/main.py
from flask import (Blueprint, 
                    request,
                    redirect,
                    render_template,
                    url_for,
                    session,
                    flash,
                    current_app
)
from flask_login import login_user, logout_user
from flask_principal import (
    Identity,
    AnonymousIdentity,
    identity_changed
)

from webapp.extensions import oid, facebook, twitter
from webapp.forms import LoginForm, RegisterForm, OpenIDForm
from webapp.models import db, User

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)

@main_blueprint.route('/')
def index():
    return redirect(url_for('catalog.home'))

@main_blueprint.route('/facebook')
def facebook_login():
    return facebook.authorize(
        callback=url_for(
            '.facebook_authorized',
            next=request.referrer or None,
            _external=True
        )
    )

@main_blueprint.route('/facebook/authorized')
@facebook.authorized_handler
def facebook_authorized(resp):
    if resp is None:
        return 'Access denied: reason=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )

    session['facebook_oauth_token'] = (resp['access_token'], '')

    me = facebook.get('/me')
    user = User.query.filter_by(
        username = me.data['name']
    ).first()

    if not user:
        user = User(me.data['name'])
        db.session.add(user)
        db.session.commit()
        login_user(user)

    #Login User here
    flash("You have been logged in.", category="success")

    return redirect(
        request.args.get('next') or url_for('catalog.home')
    )

@main_blueprint.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    form = LoginForm()
    openid_form = OpenIDForm()

    if openid_form.validate_on_submit():
        return oid.try_login(
            openid_form.openid.data,
            ask_for=['nickname', 'email'],
            ask_for_opitonal=['fullname']
        )

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user, remember=form.remember.data)

        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.id)
        )

        flash("You have been logged in.", category="success")
        return redirect(url_for('catalog.home'))

    openid_errors = oid.fetch_error()
    if openid_errors:
        flash(openid_errors, category="danger")

    return render_template('login.html', form=form, openid_form=openid_form)

@main_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()

    identity_changed.send(
        current_app._get_current_object(),
        identity=AnonymousIdentity()
    )

    flash("You have been logged out.", category="success")
    return redirect(url_for('catalog.home'))

@main_blueprint.route('/register', methods=['GET', 'POST'])
@oid.loginhandler
def register():
    form = RegisterForm()
    openid_form = OpenIDForm()

    if openid_form.validate_on_submit():
        return oid.try_login(
            openid_form.openid.data,
            ask_for=['nickname', 'email'],
            ask_for_opitonal=['fullname']
        )

    if form.validate_on_submit():
        new_user = User(form.username.data)
        new_user.set_password(form.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash(
            "Your user has been created, please login.",
            category="success"
        )
        return redirect(url_for('.login'))

    openid_errors = oid.fetch_error()
    if openid_errors:
        flash(openid_errors, category="danger")

    return render_template('register.html', form=form)

@main_blueprint.route('/twitter-login')
def twitter_login():
    return twitter.authorize(
        callback=url_for(
            '.twitter_authorized',
            next=request.referrer or None,
            _external=True
        )
    )

@main_blueprint.route('/twitter-login/authorized')
@twitter.authorized_handler
def twitter_authorized(resp):
    if resp is None:
        return 'Access denied: reason {} error {}'.format(
            request.args['error_reason'],
            request.args['error_description']
        )

    session['twitter_oauth_token'] = resp['oauth_token'] + \
        resp['oauth_token_secret']

    user = User.query.filter_by(
        username=resp['screen_name']
    ).first()

    if not user:
        user = User(resp['screen_name'])
        db.session.add(user)
        db.session.commit()
        login_user(user)

    # Login User here
    flash("You have been logged in.", category="success")

    return redirect(
        request.args.get('next') or url_for('catalog.home')
    )

vagrant/item_catalog/webapp/controllers/rest/auth.py
from flask import abort, current_app
from flask_restful import Resource

from webapp.models import db, User
from .parsers import user_post_parser
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

class AuthApi(Resource):
	def post(self):
		args = user_post_parser.parse_args()
		user = User.query.filter_by(
			username=args['username']
		).one()

		if user.check_password(args['password']):
			s = Serializer(
				current_app.config['SECRET_KEY'],
				expires_in=600
			)
			return {"token": s.dumps({"id": user.id})}
		else:
			abort(401)

vagrant/item_catalog/webapp/templates/main/base.html
<!-- TODO: Figure out why pagination isn't working -->
{% macro render_pagination(pagination, endpoint) %}
	<nav>
		<ul class="pagination">
			<li>
				<a href="{{url_for('.home', page=pagination.prev().page) }}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
				</a>
			</li>
			{% for page in pagination.iter_pages() %}
				{% if page %}
					{% if page != pagination.page %}
						<li>
							<a href="{{ url_for(endpoint, page=page) }}">
								{{ page }}
							</a>
						</li>
					{% else %}
						<li><a href="">{{ page }}</a></li>
					{% endif %}
				{% else %}
					<li><a>...</a></li>
				{% endif %}
			{% endfor %}
		</ul>
	</nav>
{% endmacro %}

{% macro side_bar(recent, top_tags) %}
	<div class="col-lg-3">
		<div class="row">
			<h5>Recent Items</h5>
			<ul>
				{% for item in recent %}
				<li>
					<a href="{{ url_for('.item', item_id = item.id ) }}"> {{ item.title }}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
		<div class="row">
			<h5>Popular Tags</h5>
			<ul>
				{% for tag in top_tags %}
				<li><a href="{{ url_for('.tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endmacro %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial- scale=1">
		<title>{% block title %}Catalog{% endblock %}</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
		{% block css %}
		{% endblock %}
	</head>
	<body>
		<div class="container">
			<div class="jumbotron">
				<h1><a href="{{ url_for('catalog.home')}}">Cataloggable</a></h1>
				<p>Welcome to the Cataloggiest Catalog ever!</p>
				{% if current_user.is_authenticated %}
					<a href="{{ url_for('main.logout')}}"><button>Logout</button></a>
				{% else %}
					<a href="{{ url_for('main.login')}}"><button>Login</button></a>
				{% endif %}
			</div>
			{% with messages = get_flashed_messages(with_categories=true) %}
		      {% if messages %}
		        {% for category, message in messages %}
		           <div class="alert alert-{{ category }} alert-dismissible" 
		             role="alert">
		           <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

		           {{ message }}
		          </div>
		        {% endfor %}
		      {% endif %}
		    {% endwith %}
			{% block body %}
			{% endblock %}
		</div>
		<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
		<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
		{% block js %}
  		{% endblock %}
	</body>
</html>

vagrant/item_catalog/webapp/templates/main/login.html
{% extends "main/base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1 class="text-center">Login</h1>
            <form method="POST" action="{{ url_for('.login') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Login">
            </form>
            <h2 class="text-center">Register With Facebook</h2>
            <a href="{{ url_for('.facebook_login') }}">Login via Facebook</a>
            <h2 class="text-center">Register With Twitter</h2>
            <a href="{{ url_for('.twitter_login') }}">Login</a>
            <hr>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

vagrant/item_catalog/webapp/templates/main/register.html
{% extends "main/base.html" %}
{% block title %}Register{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1 class="text-center">Register</h1>
            <form method="POST" action="{{ url_for('.register') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.confirm.label }}
                    {% if form.confirm.errors %}
                        {% for e in form.confirm.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.confirm(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.recaptcha.label }}
                    {% if form.recaptcha.errors %}
                        {% for e in form.recaptcha.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.recaptcha(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Register">
            </form>
            <hr>
            <h2 class="text-center">Register With Facebook</h2>
            <a href="{{ url_for('.facebook_login') }}">Login via Facebook</a>
            <h2 class="text-center">Register With Twitter</h2>
            <a href="{{ url_for('.twitter_login') }}">Login</a>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}